# Laboratorio Teoría de Modelos y simulación de sistemas
## Capítulo 1. Matrices

En Python se pueden manipular listas y matrices sin necesidad de una librería especial. Sin embargo, NumPy (Numerical Python) es una biblioteca libre ampliamente usada en ingeniería debido a la gran cantidad de beneficios que proporciona a la hora de manipular datos.

- Para usar Numpy es necesario instalar la librería: `pip install numpy`.
- Una vez instalada, en cada script es necesario importarla.

In [1]:
import numpy as np

## 1.1. Generación de matrices y manipulación de elementos

**Ejemplo 1: Inicializar un vector**

In [2]:
B = np.array([1, 5, 9, 4, 6, 7, 3, 8, 2])
print(B)

[1 5 9 4 6 7 3 8 2]


**Ejemplo 2: Inicializar una matriz bidimensional**

In [3]:
A = np.array([[1, 5, 4], [2, 3, 6], [4, 8, 9]])
print(A)

[[1 5 4]
 [2 3 6]
 [4 8 9]]


**Ejemplo 3:** Acceder al tercer elemento de la segunda fila de la matriz A. Las matrices de Numpy empiezan su numeración en 0.

In [4]:
element = A[1, 2]
print("Matrix at 2 row and 3 column = ", element)

Matrix at 2 row and 3 column =  6


**Ejemplo 4:** Calcular manualmente el producto escalar entre la primera y tercera columna de A.

In [5]:
esc = A[0,0] * A[0,2] + A[1,0] * A[1,2] + A[2,0] * A[2,2]
print(esc)

52


**Ejemplo 5:** Acceder a la segunda columna y a la tercera fila de A.

In [6]:
row_3 = A[2, :]
column_2 = A[:, 1]
print(row_3)
print(column_2)

[4 8 9]
[5 3 8]


## 1.2. Operaciones

**Ejemplo 1:** Elevar todos los elementos de la matriz A al cuadrado.

In [7]:
A_squared = A ** 2
print(A_squared)

[[ 1 25 16]
 [ 4  9 36]
 [16 64 81]]


**Ejemplo 2:** Multiplicar todos los elementos de la matriz A por 1.6.

In [8]:
new_A = A * 1.6
print(new_A)

[[ 1.6  8.   6.4]
 [ 3.2  4.8  9.6]
 [ 6.4 12.8 14.4]]


**Ejemplo 3:** Crear una matriz B, (a) hacer el producto matricial y (b) hacer la multiplicación elemento a elemento.

In [9]:
B = np.array([[2, 1, 3], [7, 1, 8], [6, 4, 5]])
# (a) producto de matrices
C = A @ B # O también: np.matmul(A, B)
print(C)
# (b) producto elemento a elemento
D = A * B
print(D)

[[ 61  22  63]
 [ 61  29  60]
 [118  48 121]]
[[ 2  5 12]
 [14  3 48]
 [24 32 45]]


**Ejemplo 4:** Encontrar las dimensiones de la matriz A y el número de elementos.

In [10]:
dimension = A.shape
total_elements = A.size
print("Dimension = ", dimension)
print("Total elements = ", total_elements)

Dimension =  (3, 3)
Total elements =  9


**Ejemplo 5:** Hallar la transpuesta de A.

In [11]:
A_transpose = A.T
print(A_transpose)

[[1 2 4]
 [5 3 8]
 [4 6 9]]


**Actividad 1:** Sumar y restar las matrices A y B.

**Ejemplo 6:** Encontrar el valor máximo y mínimo de la matriz B.

In [12]:
max_B = np.max(B)
min_B = np.min(B)
print("Max = ", max_B, "Min = ", min_B)

Max =  8 Min =  1


**Actividad:** Consultar la documentación de `np.max` y `np.min` para ver cómo obtener el índice del valor máximo y mínimo. Además, investigar cómo utilizar el parámetro `axis`.

## 1.3. Construcción de submatrices

Numpy posee una serie de funciones útiles para crear matrices comúnmente utilizadas:

- `np.zeros()` = matriz de ceros
- `np.ones()` = matriz de unos
- `np.empty()` = matriz cuyo contenido inicial es aleatorio
- `np.arange()` = matriz en un rango de elementos
- `np.linspace()` = matriz con valores espaciados linealmente en un intervalo especificado

**Actividad 1:** Hacer una matriz por cada una de las funciones mencionadas.

**Ejercicio 1:** Crear una submatriz con los elementos de la primera y última columna de la matriz C.

In [13]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
sub_C = C[:, [0,2]]
print(sub_C)

[[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


**Ejercicio 2:** Crear una submatriz con los elementos de la segunda y tercera fila de la matriz C.

In [14]:
sub_C = C[[1,2], :]
print(sub_C)

[[4 5 6]
 [7 8 9]]


**Ejercicio 3:** Concatenar las matrices A y B.

In [15]:
mat_conc_0 = np.concatenate((A, B), axis=0)
mat_conc_1 = np.concatenate((A, B), axis=1)
# Tarea: consultar el significado del parámetro 'axis'
print(mat_conc_0)
print(mat_conc_1)

[[1 5 4]
 [2 3 6]
 [4 8 9]
 [2 1 3]
 [7 1 8]
 [6 4 5]]
[[1 5 4 2 1 3]
 [2 3 6 7 1 8]
 [4 8 9 6 4 5]]


## 1.4. Representación de polinomios

**Ejemplo 1:** Ingresar el polinomio. Los polinomios se pueden expresar ingresando en la función los coeficientes de la expresión como un vector.

In [16]:
p = np.poly1d([1, 4, 5, 0, 2])
print(p)

   4     3     2
1 x + 4 x + 5 x + 2


**Ejemplo 2:** Evaluar el polinomio en `x = 0.5`.

In [17]:
p(0.5)

np.float64(3.8125)

Los polinomios se pueden sumar, restar, multiplicar y dividir (devuelve el cociente y el resto).

**Ejemplo 3:** Multiplicar los polinomios `p1` y `p2`.

In [18]:
p1 = np.poly1d([1, 2, 3])
p2 = np.poly1d([1, 0, 3])
p12 = p1*p2
print(p12)

   4     3     2
1 x + 2 x + 6 x + 6 x + 9


**Ejemplo 4:** Dividir el polinomio `p` por el polinomio `s = x + 1`.

In [19]:
s = np.poly1d([1, 1])
cociente, residuo = p / s
print(cociente)
print(residuo)

   3     2
1 x + 3 x + 2 x - 2
 
4


**Ejemplo 5:** Hallar las raíces del polinomio.

In [20]:
roots = p.r
print(roots)

[-2.12881842+1.10325521j -2.12881842-1.10325521j  0.12881842+0.57557796j
  0.12881842-0.57557796j]
