# **Matrices**

Para manejar las matrices vamos a trabajarcon Numpy, para eso vamos a importarlo de la siguiente manera:


In [ ]:
import numpy as np

Vector = np.array([8,5,4,1,4,1,5,4,5]) #De esta manera inicializamos un vector

vector_bi = np.array([[8,5,1,2],[6,5,4,1]]) #Asi genero una matriz, recuerda ponerle doble [], deben tener la misma dimension.

elemento = vector_bi[1,2] #ASi llamo al elemto de la matriz, [Ubicacion de la Fila,Ubicacion de las columnas]

print("El valor de la fila 2 y columna 3 es:", elemento)

producto_escalar = vector_bi[0,1]*vector_bi[0,3] + vector_bi[1,1]*vector_bi[1,3] #Calculo es producto escalar de manera manual, de la segunda y cuarta columna.
print(producto_escalar)

columna_2  = vector_bi[:,1] #Asi hago para imprimir toda una columna
fila_1 = vector_bi[0,:]# Asi hago para imprimir toda una fila

print(f'Columna2: {columna_2}\nFila1: {fila_1} ')

matriz_alCuadrado = vector_bi**2 # Esto eleva todos los valores de la matriz al cuadrado
print(f'\n{matriz_alCuadrado}')

multiPor_X = vector_bi*5 #multiplica todos los valores de las matrices por el valor X deseado
print(f'\n{multiPor_X}')

#----------------------------------------------------
#Ahora, creamos una matriz B y la vamos a utilizar para hacer una multiplicacion matricial y otra termino a termino
Be = np.array([[9,5],[2,4],[45,2],[63,4]]) #Recoredemos las propiedas de las matrices:
#Si queremos multiplicar dos matrices, deben cumplir que en sus dimensiones,
#AxB y ZxH, B y Z deben ser iguales. Donde A y Z son filas y B y H columnas.

print("------------------------------------------------------------------")

producto_matricial= vector_bi @ Be #Otra forma es np.matmul(vector_bi,B). 
#Ell producto matricial no conmuta

print('\n',producto_matricial)

A = np.array([[0,5],[99,5]])
Ce = np.array([[2,6],[6,7]])
De = A * Ce #Asi de multiplica producto elemento a elemento. Estas deben ser de igual dimension 

dimension = Be.shape #asi encuentro la dimesion de la matriz
total_elementos = Be.size

print(f"\nDimension:{dimension}\nTotal elementos:{total_elementos}")

#-------------------------------------------------------------------

#Hallar la transpuesta

transpuesta = Be.T

#Sumar y restas matrices

suma = A + Ce #Reocardar tener las mismas dimensiones

resta = A - Ce

print(f"\nTranspuesta:{transpuesta}\nSuma:{suma}\nResta:{resta}")

#Para consultar Max y Min uso np.max() y np.min()

El valor de la fila 2 y columna 3 es: 4
15
Columna2: [5 5]
Fila1: [8 5 1 2] 

[[64 25  1  4]
 [36 25 16  1]]

[[40 25  5 10]
 [30 25 20  5]]
------------------------------------------------------------------

 [[253  70]
 [307  62]]

Dimension:(4, 2)
Total elementos:8

Transpuesta:[[ 9  2 45 63]
 [ 5  4  2  4]]
Suma:[[  2  11]
 [105  12]]
Resta:[[-2 -1]
 [93 -2]]


np.zeros() = matriz de ceros

np.ones() = matriz de unos

np.empty() = matriz cuyo contenido inicial es aleatorio

np.arange() = matriz en un rango de elementos

np.linspace() = mstriz con valores espaciados linealmente en un intervalo especificado

In [ ]:
ceros = np.zeros((4,3))
print(ceros)
unos = np.ones((2,2))
print('\n',unos)
aleatorio = np.empty((3,2))
print('\n',aleatorio)
rango = np.arange(1,10).reshape(3,3)#asi se hace para generar una matriz aca, reshape cambia la matriz
print('\n',rango)
espaciado = np.linspace(2,4)
print('\n',espaciado)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1.]
 [1. 1.]]

 [[1.79769313e+308 1.79769313e+308]
 [2.00000000e+000 2.22044605e-016]
 [2.22507386e-308 4.94065646e-324]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 50
