# **Punto 1**

Crear dos vectores, A y B, aleatorios enteros (puede usar la función np.random.randint) con
dimensiones 1 x 4. Crear una matriz con las siguientes consideraciones:

Columna 1:
Suma de los vectores A y B

Columna 2:
Multiplicación de A y B

Columna 3:
Vector A al cuadrado

Columna 4:
Vector B al cuadrado

In [21]:
import numpy as np
np.random.seed(1)
A = np.random.randint(0,50,4)
print(A)
B = np.random.randint(0,50,4)
print(B)
#Para formar una matriz desde sus columnas uso la funcion np.columns_stack
columna1 = A + B
columna2 = A*B
columna3 = A**2
columna4 = B**2
C = np.column_stack((columna1,columna2,columna3,columna4))
print(C)

[37 43 12  8]
[ 9 11  5 15]
[[  46  333 1369   81]
 [  54  473 1849  121]
 [  17   60  144   25]
 [  23  120   64  225]]


# **Punto 2**

Sean los vectores X = [2 6 8 9 0 1 8], Y = [0 1 3 6 4 2 7]:

a. Calcular el valor máximo y mínimo de cada vector e indicar la posición de dicho valor.

b. Crear un vector N en el que cada elemento i corresponderá al valor presentado en la tabla según
la relación de los elementos de X y Y.

Relación
N(i)
X(i) = Y(i)
0

X(i) > Y(i)
1

X(i) < Y(i)
-1

c. Encontrar la posición de los valores nulos en cada vector y reemplazar por el número de la
posición encontrada.

In [ ]:
import numpy as np

# Vectores
X = np.array([2, 6, 8, 9, 0, 1, 8])
Y = np.array([0, 1, 3, 6, 4, 2, 7])


# -------------------------
# a) Máximo, mínimo y posición
# -------------------------

max_X = np.max(X)
min_X = np.min(X) #Otra forma de saber el indicie del max o min es con la funcion np.argmax() y np.argmin()

pos_max_X = np.where(X == max_X)[0]
pos_min_X = np.where(X == min_X)[0]

print("X")
print("Máximo:", max_X)
print("Posición máximo:", pos_max_X)
print("Mínimo:", min_X)
print("Posición mínimo:", pos_min_X)


max_Y = np.max(Y)
min_Y = np.min(Y)

pos_max_Y = np.where(Y == max_Y)[0]
pos_min_Y = np.where(Y == min_Y)[0]

print("\nY")
print("Máximo:", max_Y)
print("Posición máximo:", pos_max_Y)
print("Mínimo:", min_Y)
print("Posición mínimo:", pos_min_Y)


# -------------------------
# b) Crear vector N
# -------------------------

N = np.where(X > Y, 1, -1)
N = np.where(X == Y, 0, N)

print("\nN =", N)


# -------------------------
# c) Buscar ceros
# -------------------------

pos_X = np.where(X == 0)[0]
pos_Y = np.where(Y == 0)[0]

print("\nPosición del cero en X:", pos_X)
print("Posición del cero en Y:", pos_Y)


# Reemplazar cero por posición
X[pos_X] = pos_X
Y[pos_Y] = pos_Y

print("X modificado:", X)
print("Y modificado:", Y)